using System;
using System.IO;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace DfTools.Generators
{
    [Generator]
    public class AppSettingsGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var appSettingsFiles = context.AdditionalTextsProvider
                .Where(static file => Path.GetFileName(file.Path).Equals("appsettings.json", StringComparison.OrdinalIgnoreCase))
                .Select(static (file, cancellationToken) => file.GetText(cancellationToken)?.ToString());

            context.RegisterSourceOutput(appSettingsFiles, static (productionContext, jsonContent) =>
            {
                if (string.IsNullOrWhiteSpace(jsonContent))
                {
                    return;
                }

                try
                {
                    var sourceText = GenerateSourceText(jsonContent!);
                    productionContext.AddSource("GeneratedAppSettings.g.cs", SourceText.From(sourceText, Encoding.UTF8));
                }
                catch (Exception ex)
                {
                    var descriptor = new DiagnosticDescriptor(
                        "AG0001",
                        "Failed to generate AppSettings",
                        "Error parsing appsettings.json: {0}",
                        "AppSettingsGenerator",
                        DiagnosticSeverity.Error,
                        isEnabledByDefault: true);

                    productionContext.ReportDiagnostic(Diagnostic.Create(descriptor, Location.None, ex.Message));
                }
            });
        }

        private static string GenerateSourceText(string jsonContent)
        {
            using var doc = JsonDocument.Parse(jsonContent);
            var root = doc.RootElement;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("namespace DfTools.Desktop.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GeneratedAppSettings");
            sb.AppendLine("    {");
            sb.AppendLine("        public static DfTools.Desktop.Models.AppSettings Default { get; } = CreateDefaultSettings();");
            sb.AppendLine();
            sb.AppendLine("        private static DfTools.Desktop.Models.AppSettings CreateDefaultSettings()");
            sb.AppendLine("        {");
            sb.AppendLine("            var settings = new DfTools.Desktop.Models.AppSettings();");

            foreach (var sectionProp in root.EnumerateObject())
            {
                var sectionName = sectionProp.Name;
                var sectionValue = sectionProp.Value;

                if (sectionValue.ValueKind == JsonValueKind.Object)
                {
                    sb.AppendLine($"            settings.{sectionName} = new DfTools.Desktop.Models.{sectionName}Settings");
                    sb.AppendLine("            {");
                    foreach (var prop in sectionValue.EnumerateObject())
                    {
                        var propName = prop.Name;
                        var propVal = prop.Value;
                        if (propVal.ValueKind == JsonValueKind.String)
                        {
                            var escapedStr = SymbolDisplay.FormatLiteral(propVal.GetString() ?? "", true);
                            sb.AppendLine($"                {propName} = {escapedStr},");
                        }
                        else if (propVal.ValueKind == JsonValueKind.Number)
                        {
                            sb.AppendLine($"                {propName} = {propVal.GetRawText()},");
                        }
                        else if (propVal.ValueKind == JsonValueKind.True || propVal.ValueKind == JsonValueKind.False)
                        {
                            sb.AppendLine($"                {propName} = {propVal.GetRawText().ToLowerInvariant()},");
                        }
                    }
                    sb.AppendLine("            };");
                }
            }

            sb.AppendLine("            return settings;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
